// Generated by CoffeeScript 1.6.3
(function() {
  var $;

  $ = jQuery;

  ({
    fate_core_dataPreLoad: function(options) {},
    fate_core_dataPostLoad: function(options) {
      return fate_core_process_skills;
    },
    fate_core_dataChange: function(options) {},
    fate_core_dataPreSave: function(options) {},
    fate_core_trim_skill_name: function(name) {
      return name.replace(/^(\s*)'|'(\s*)$/g, '');
    },
    fate_core_skill_html: function(skill) {
      return '<li>' + skill + '</li>';
    },
    fate_core_process_skills: function() {
      var html, skill_container, skill_containers, skills;
      skill_containers = $('.skills').children().children('.dsf');
      skill_container = skill_containers.first();
      skills = skill_container.text().split(',').map(fate_core_trim_skill_name);
      html = '<ul>' + skills.map(fate_core_skill_html).join('') + '</ul>';
      console.log(skills);
      return skill_container.html(html);
    }
  });

}).call(this);
