// Generated by CoffeeScript 1.6.3
(function() {
  var $;

  $ = jQuery;

  window.fate_core_dataPreLoad = function(options) {};

  window.fate_core_dataPostLoad = function(options) {
    fate_core_mark_used_skills();
    fate_core_set_active_stress_boxes();
    fate_core_set_active_stress_tracks();
    fate_core_set_active_consequences();
    fate_core_size_avatar();
    fate_core_size_points();
    fate_core_default_extra_consequences();
    fate_core_default_skill_names();
    return fate_core_resize_name();
  };

  window.fate_core_dataChange = function(options) {
    fate_core_update_skill(options);
    fate_core_update_active_stress(options);
    fate_core_update_active_stress_tracks(options);
    fate_core_update_active_consequences(options);
    fate_core_size_points();
    fate_core_default_extra_consequences();
    return fate_core_default_skill_names();
  };

  window.fate_core_dataPreSave = function(options) {};

  window.fate_core_resize_name = function() {
    return setTimeout((function() {
      var name, size, _results;
      name = $('.dsf_name')[0];
      size = 22;
      name.style.fontSize = "" + size + "px";
      _results = [];
      while (name.offsetWidth > 235) {
        size--;
        _results.push(name.style.fontSize = "" + size + "px");
      }
      return _results;
    }), 1000);
  };

  window.fate_core_default_skill_names = function() {
    var skill, skills, _i, _len, _results;
    skills = $('.skill_name');
    _results = [];
    for (_i = 0, _len = skills.length; _i < _len; _i++) {
      skill = skills[_i];
      if (skill.innerHTML === aisleten.characters.jeditablePlaceholder || skill.innerHTML === '') {
        if (skill.classList.contains('dsf_skill_1_label')) {
          _results.push(skill.innerHTML = 'Average (+1)');
        } else if (skill.classList.contains('dsf_skill_2_label')) {
          _results.push(skill.innerHTML = 'Fair (+2)');
        } else if (skill.classList.contains('dsf_skill_3_label')) {
          _results.push(skill.innerHTML = 'Good (+3)');
        } else if (skill.classList.contains('dsf_skill_4_label')) {
          _results.push(skill.innerHTML = 'Great (+4)');
        } else if (skill.classList.contains('dsf_skill_5_label')) {
          _results.push(skill.innerHTML = 'Superb (+5)');
        } else if (skill.classList.contains('dsf_skill_6_label')) {
          _results.push(skill.innerHTML = 'Fantastic (+6)');
        } else {
          _results.push(void 0);
        }
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  window.fate_core_default_extra_consequences = function() {
    var consequence, consequences, label, title, _i, _len, _results;
    consequences = $('.consequence');
    _results = [];
    for (_i = 0, _len = consequences.length; _i < _len; _i++) {
      consequence = consequences[_i];
      label = consequence.children[0];
      title = consequence.children[1];
      if (label.innerHTML === aisleten.characters.jeditablePlaceholder || label.innerHTML === '') {
        if (consequence.classList.contains('mild')) {
          label.innerHTML = '2';
          _results.push(title.innerHTML = 'Mild');
        } else if (consequence.classList.contains('moderate')) {
          label.innerHTML = '4';
          _results.push(title.innerHTML = 'Moderate');
        } else if (consequence.classList.contains('severe')) {
          label.innerHTML = '6';
          _results.push(title.innerHTML = 'Severe');
        } else {
          label.innerHTML = '2';
          _results.push(title.innerHTML = 'Extra');
        }
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  window.fate_core_size_points = function() {
    var point, points, _i, _len, _results;
    points = $('.points_box').children('.grey').children('.dsf');
    _results = [];
    for (_i = 0, _len = points.length; _i < _len; _i++) {
      point = points[_i];
      if (point.innerHTML === aisleten.characters.jeditablePlaceholder || point.innerHTML === '') {
        _results.push(point.classList.add('placeholder'));
      } else {
        _results.push(point.classList.remove('placeholder'));
      }
    }
    return _results;
  };

  window.fate_core_size_avatar = function() {
    var avatar;
    avatar = $('.dsf_avatar_image').children().first();
    return avatar.load(function() {
      var height, width;
      height = avatar.height();
      width = avatar.width();
      if (height > width) {
        return avatar.addClass('tall');
      } else {
        return avatar.addClass('wide');
      }
    });
  };

  window.fate_core_set_active_consequences = function() {
    var activator, consequence, consequences, on_value, _i, _len, _results;
    consequences = $('.consequence');
    _results = [];
    for (_i = 0, _len = consequences.length; _i < _len; _i++) {
      consequence = consequences[_i];
      activator = consequence.children[3].children[0].children[0];
      if (consequence.classList.contains('extra')) {
        on_value = '1';
      } else {
        on_value = '0';
      }
      if (activator.value === on_value) {
        consequence.classList.add('active');
        _results.push(consequence.classList.remove('inactive'));
      } else {
        consequence.classList.add('inactive');
        _results.push(consequence.classList.remove('active'));
      }
    }
    return _results;
  };

  window.fate_core_set_active_stress_tracks = function() {
    var activator, track, tracks, _i, _len, _results;
    tracks = $('.stress_track');
    _results = [];
    for (_i = 0, _len = tracks.length; _i < _len; _i++) {
      track = tracks[_i];
      activator = track.children[1].children[0].children[0];
      if (activator.value === '0') {
        track.classList.add('inactive');
        _results.push(track.classList.remove('active'));
      } else {
        track.classList.add('active');
        _results.push(track.classList.remove('inactive'));
      }
    }
    return _results;
  };

  window.fate_core_set_active_stress_boxes = function() {
    var activator, entry, group, stresses, _i, _len, _results;
    stresses = $('td.stress');
    _results = [];
    for (_i = 0, _len = stresses.length; _i < _len; _i++) {
      entry = stresses[_i];
      group = entry.children[0];
      activator = entry.children[1].children[0].children[0];
      if (activator.value === '0') {
        _results.push(group.classList.add('inactive'));
      } else {
        _results.push(group.classList.add('active'));
      }
    }
    return _results;
  };

  window.fate_core_mark_used_skills = function() {
    var content, listing, listings, _i, _len, _results;
    listings = $('.skill.inactive');
    _results = [];
    for (_i = 0, _len = listings.length; _i < _len; _i++) {
      listing = listings[_i];
      content = listing.childNodes[1].innerHTML.trim();
      if (content.length > 0) {
        _results.push(listing.className = 'skill');
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  window.fate_core_update_active_consequences = function(opts) {
    var consequence, container, match, name, on_value, value;
    name = opts['fieldName'];
    value = opts['fieldValue'];
    match = name.match(/((\w+)(_\d\d)?)_consequence_activator/);
    if (!match) {
      return;
    }
    consequence = $(".dsf_" + match[1] + "_consequence_activator");
    container = consequence.parent().parent()[0];
    if (container.classList.contains('extra')) {
      on_value = '1';
    } else {
      on_value = '0';
    }
    if (value === on_value) {
      container.classList.add('active');
      return container.classList.remove('inactive');
    } else {
      container.classList.add('inactive');
      return container.classList.remove('active');
    }
  };

  window.fate_core_update_active_stress_tracks = function(opts) {
    var match, name, track, value;
    name = opts['fieldName'];
    value = opts['fieldValue'];
    match = name.match(/extra_(\d\d)_stress_active/);
    if (!match) {
      return;
    }
    track = $(".dsf_extra_" + match[1] + "_stress_active");
    if (value === '0') {
      track.parent().parent().addClass('inactive');
      return track.parent().parent().removeClass('active');
    } else {
      track.parent().parent().addClass('active');
      return track.parent().parent().removeClass('inactive');
    }
  };

  window.fate_core_update_active_stress = function(opts) {
    var match, name, stress, value;
    name = opts['fieldName'];
    value = opts['fieldValue'];
    match = name.match(/(\w+)_stress_(\d\d)_active/);
    if (!match) {
      return;
    }
    stress = $(".dsf_" + match[1] + "_stress_" + match[2]);
    if (value === "1") {
      stress.parent().addClass('active');
      return stress.parent().removeClass('inactive');
    } else {
      stress.parent().addClass('inactive');
      return stress.parent().removeClass('active');
    }
  };

  window.fate_core_update_skill = function(opts) {
    var match, name, skill, value;
    name = opts['fieldName'];
    value = opts['fieldValue'];
    match = name.match(/skill_(\w+)_(\d\d)/);
    if (!match) {
      return;
    }
    skill = $(".dsf_" + name).first();
    if (skill.text() === aisleten.characters.jeditablePlaceholder || skill.text() === '') {
      return skill.parent().addClass('inactive');
    } else {
      return skill.parent().removeClass('inactive');
    }
  };

}).call(this);
